/**
 * AI MERCHANT MARKETING & PROMOTION COUPON ENGINE (aiMarketingService.js)
 * Intelligent Marketing Strategist for Canteen Shops.
 * Analyzes peak/low hours, customer retention, and generates high-converting coupons with 1-Click Deployment.
 */

const ACTIVE_COUPONS_STORAGE_KEY = "queueup_active_merchant_coupons_v1";

/**
 * 1. AI Marketing Analytics & Strategic Promotion Recommendation Engine
 * Analyzes store performance parameters to output customized coupon packages.
 * @param {object} storeMetrics - { totalSalesToday: number, totalOrdersToday: number, topSellerDish: string, currentHour: number }
 * @returns {Array<object>} Array of recommended coupon packages with ROI predictions
 */
export function generateAIMarketingRecommendations() {
  const recommendations = [];

  // Strategy A: Off-Peak Hours Booster (Happy Hour Coupon)
  // If off-peak (e.g. 13:00 - 15:00) or high slow time
  recommendations.push({
    id: "AI-COUPON-HAPPY-HOUR",
    title: "⚡ คูปองกระตุ้นยอดขายช่วงบ่าย (Happy Hour 13:00-14:30 น.)",
    discountType: "PERCENT",
    discountValue: 15, // 15% Off
    minSpend: 50,
    code: "HAPPY15",
    description: "ลด 15% เมื่อสั่งครบ ฿50 ในช่วงหลังพักเที่ยง เพื่อดึงดูดนักเรียนและบุคลากรที่มารับประทานรอบบ่าย",
    targetAudience: "นักเรียนหลังคาบบ่าย & ครูบุคลากร",
    projectedSalesIncrease: "+25% ยอดขายช่วงบ่าย",
    recommendedBadge: "แนะนำสูงสุด 🔥",
    aiRationale: "จากสถิติโรงอาหาร ช่วงเวลา 13:00-14:30 น. ลูกค้าจะลดลง 40% การระเบิดโปรส่วนลดชั่วคราวจะช่วยดันยอดขายวัตถุดิบที่เหลือได้คุ้มค่าที่สุด",
  });

  // Strategy B: Student High Value Combo / Student Deal
  recommendations.push({
    id: "AI-COUPON-STUDENT-COMBO",
    title: "🎓 คูปองชุดคอมโบสุดคุ้มประจำโรงเรียน (อิ่มประหยัด)",
    discountType: "FIXED",
    discountValue: 10, // ฿10 Off
    minSpend: 60,
    code: "STUDENT10",
    description: "ส่วนลด ฿10 ทันทีเมื่อสั่งเมนูหลักคู่กับน้ำดื่มหรือไข่ดาวพิเศษ",
    targetAudience: "นักเรียนสายกิน & กลุ่มเพื่อน",
    projectedSalesIncrease: "+30% บิลเฉลี่ยต่อคน (Basket Size)",
    recommendedBadge: "เพิ่มยอดต่อบิล 💡",
    aiRationale: "นักเรียนชอบสั่งเป็นกลุ่ม การเสนอส่วนลดท้ายบิลเมื่อเพิ่มท็อปปิ้งจะเพิ่มกำไรสุทธิต่อบิลขึ้น ฿15-20 บาท",
  });

  // Strategy C: Repeat Customer Loyalty Reward Coupon
  recommendations.push({
    id: "AI-COUPON-LOYALTY",
    title: "🌟 คูปองขอบคุณลูกค้าประจำ (Loyalty VIP Canteen)",
    discountType: "FIXED",
    discountValue: 12, // ฿12 Off
    minSpend: 70,
    code: "VIPQUEUE",
    description: "มอบคูปองส่วนลด ฿12 สำหรับลูกค้าที่สั่งสะสมครบ 3 คิวขึ้นไป",
    targetAudience: "ลูกค้าประจำสะสมแต้ม",
    projectedSalesIncrease: "+40% การกลับมาสั่งซ้ำ (Retention)",
    recommendedBadge: "มัดใจลูกค้าประจำ 💖",
    aiRationale: "การสร้างความจงรักภักดีต่อร้านค้าทำให้นักเรียนกลับมาอุดหนุนร้านเดิมอย่างน้อย 4 วัน/สัปดาห์",
  });

  return recommendations;
}

/**
 * 2. Get Currently Deployed Live Shop Coupons
 * @param {string} storeId - Store ID to fetch coupons for
 * @returns {Array<object>} List of active coupons visible to customers
 */
export function getActiveMerchantCoupons(storeId = "") {
  try {
    if (!storeId) return [];
    const key = `queueup_merchant_coupons_${storeId}`;
    const raw = localStorage.getItem(key) || localStorage.getItem(ACTIVE_COUPONS_STORAGE_KEY);
    if (raw) {
      return JSON.parse(raw);
    }
    return [];
  } catch {
    return [];
  }
}

/**
 * 3. 1-Click Deploy AI Recommended Coupon
 * Merchants click 1-button to launch a coupon live into the system!
 * @param {object} couponObj - The coupon object generated by AI
 * @param {string} storeId - Store ID deploying the coupon
 */
export function deployAICoupon(couponObj, storeId = "") {
  if (!couponObj || !couponObj.code) return false;

  try {
    const activeCoupons = getActiveMerchantCoupons(storeId);

    // Check if already deployed
    const existingIndex = activeCoupons.findIndex((c) => c.code === couponObj.code);

    const newCoupon = {
      ...couponObj,
      storeId,
      isActive: true,
      deployedAt: new Date().toISOString(),
    };

    if (existingIndex >= 0) {
      activeCoupons[existingIndex] = newCoupon;
    } else {
      activeCoupons.unshift(newCoupon);
    }

    const key = `queueup_merchant_coupons_${storeId}`;
    localStorage.setItem(key, JSON.stringify(activeCoupons));
    return true;
  } catch {
    return false;
  }
}

/**
 * 4. Toggle Coupon Active State
 */
export function toggleCouponState(code, storeId = "") {
  try {
    const activeCoupons = getActiveMerchantCoupons(storeId);
    const updated = activeCoupons.map((c) => {
      if (c.code === code) {
        return { ...c, isActive: !c.isActive };
      }
      return c;
    });
    const key = `queueup_merchant_coupons_${storeId}`;
    localStorage.setItem(key, JSON.stringify(updated));
    return updated;
  } catch {
    return getActiveMerchantCoupons(storeId);
  }
}

/**
 * 5. Validate & Apply Coupon Code on Customer Checkout
 * @param {string} code - Entered coupon code
 * @param {number} totalAmount - Current order total amount
 * @returns {object} { valid: boolean, discountAmount: number, message: string }
 */
export function applyCouponToOrder(code, totalAmount) {
  if (!code || typeof code !== "string") {
    return { valid: false, discountAmount: 0, message: "กรุณาระบุรหัสคูปอง" };
  }

  const cleanCode = code.trim().toUpperCase();
  const coupons = getActiveMerchantCoupons();
  const target = coupons.find((c) => c.code.toUpperCase() === cleanCode && c.isActive);

  if (!target) {
    return {
      valid: false,
      discountAmount: 0,
      message: `ไม่พบคูปอง "${cleanCode}" หรือคูปองหมดอายุแล้ว`,
    };
  }

  if (totalAmount < target.minSpend) {
    return {
      valid: false,
      discountAmount: 0,
      message: `คูปองนี้ใช้ได้เมื่อสั่งซื้อขั้นต่ำ ฿${target.minSpend} บาทขึ้นไป (ขาดอีก ฿${target.minSpend - totalAmount} บาท)`,
    };
  }

  const calculatedDiscount = target.discountType === "PERCENT"
    ? Math.round((totalAmount * target.discountValue) / 100)
    : target.discountValue;

  // Ensure discount does not exceed total
  const discountAmount = Math.min(calculatedDiscount, totalAmount);

  return {
    valid: true,
    discountAmount,
    couponTitle: target.title,
    message: `ใช้งานคูปอง "${target.code}" สำเร็จ! รับส่วนลด ฿${discountAmount} บาท 🎉`,
  };
}
